elasticsearch:
  uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
  username: ${ELASTICSEARCH_USERNAME:elastic}
  password: ${ELASTICSEARCH_PASSWORD:elastic}


keycloak:
  host: ${KEYCLOAK_HOST:http://localhost:8443}
  realm: ${KEYCLOAK_REALM:codeflix}

server:
  port: 8080
  undertow:
    threads:
      worker: 64
      io: 4
