elasticsearch:
  connect-timeout: 250
  socket-timeout: 1_000

graphql:
  graphiql: false

kafka:
  auto-create-topics: false
  bootstrap-servers: localhost:9092
  pool-timeout: 1_000
  consumers:
    categories:
      auto-offset-reset: earliest
      concurrency: 1
      id: kafka-listener-categories
      topics: adm_videos_mysql.adm_videos.categories
      group-id: catalogo-service

logging:
  level:
    ROOT: INFO
    com.yansb.admin.api: DEBUG

server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  undertow:
    threads:
      worker: 64
      io: 4

spring:
  graphql:
    graphiql:
      enabled: ${graphql.graphiql}
  elasticsearch:
    uris: ${elasticsearch.uris}
    username: ${elasticsearch.username}
    password: ${elasticsearch.password}
    socket-timeout: ${elasticsearch.socket-timeout}
    connection-timeout: ${elasticsearch.connect-timeout}
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 100GB
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.host}/realms/${keycloak.realm}/protocol/openid-connect/certs
          issuer-uri: ${keycloak.host}/realms/${keycloak.realm}